// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0_w58uByjvEmc_dlNVIckZms0jf4OiQ',
    appId: '1:1049965475174:web:3f56c0c2e4987d7e3f04a7',
    messagingSenderId: '1049965475174',
    projectId: 'push-notification-3a0f0',
    authDomain: 'push-notification-3a0f0.firebaseapp.com',
    storageBucket: 'push-notification-3a0f0.appspot.com',
    measurementId: 'G-WKVG7985RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZucDQmCADcQPeVsRDNDSOcI6F_-WOu8',
    appId: '1:1049965475174:android:beabc4af659c98293f04a7',
    messagingSenderId: '1049965475174',
    projectId: 'push-notification-3a0f0',
    storageBucket: 'push-notification-3a0f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgaqEDc21AvhDMiRw2xMHIhvt6nflqywM',
    appId: '1:1049965475174:ios:7b86606a2f2063b23f04a7',
    messagingSenderId: '1049965475174',
    projectId: 'push-notification-3a0f0',
    storageBucket: 'push-notification-3a0f0.appspot.com',
    iosBundleId: 'ch.glab.app.oddsandevens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgaqEDc21AvhDMiRw2xMHIhvt6nflqywM',
    appId: '1:1049965475174:ios:7b86606a2f2063b23f04a7',
    messagingSenderId: '1049965475174',
    projectId: 'push-notification-3a0f0',
    storageBucket: 'push-notification-3a0f0.appspot.com',
    iosBundleId: 'ch.glab.app.oddsandevens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo0_w58uByjvEmc_dlNVIckZms0jf4OiQ',
    appId: '1:1049965475174:web:899a6469c49d1abe3f04a7',
    messagingSenderId: '1049965475174',
    projectId: 'push-notification-3a0f0',
    authDomain: 'push-notification-3a0f0.firebaseapp.com',
    storageBucket: 'push-notification-3a0f0.appspot.com',
    measurementId: 'G-CH6SK0HHV4',
  );
}